# Jia Zeng 8936740 - Lab 3
---
# Part A

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [12]:
df_cc = pd.read_csv("./creditcard.csv")
#df_cc.head()

In [7]:
df_cc.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [20]:
# check data there's any null
print(df_cc.isnull().sum().max()) # max() for finding if there is not 0

0

In [22]:
X = df_cc.drop('Class', axis=1)
y = df_cc['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [28]:
y_pred = model.predict(X_test_scaled)
print(f'Accuracy score: {round((accuracy_score(y_test, y_pred) * 100), 2)}%')

Accuracy score: 99.93%

# Part B

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [51]:
df_i = pd.read_csv("./insurance.csv")
df_i.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [69]:
#change the string to num
sex_mapping = {'female': 1, 'male': 2}
df_i['sex'] = df_i['sex'].map(sex_mapping)
smoker_mapping = {'yes': 1, 'no': 2}
df_i['smoker'] = df_i['smoker'].map(smoker_mapping)
region_mapping = {'southwest': 1, 'southeast': 2, 'northwest': 3, 'northeast': 4}
df_i['region'] = df_i['region'].map(region_mapping)
df_i.head()

   age  sex     bmi  children  smoker  region      charges
0   19  NaN  27.900         0     NaN     NaN  16884.92400
1   18  NaN  33.770         1     NaN     NaN   1725.55230
2   28  NaN  33.000         3     NaN     NaN   4449.46200
3   33  NaN  22.705         0     NaN     NaN  21984.47061
4   32  NaN  28.880         0     NaN     NaN   3866.85520

In [53]:
df_i.describe()

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000
mean,39.207025,1.505232,30.663397,1.094918,1.795217,2.484305,13270.422265
std,14.049960,0.500160,6.098187,1.205493,0.403694,1.104885,12110.011237
min,18.000000,1.000000,15.960000,0.000000,1.000000,1.000000,1121.873900
25%,27.000000,1.000000,26.296250,0.000000,2.000000,2.000000,4740.287150
50%,39.000000,2.000000,30.400000,1.000000,2.000000,2.000000,9382.033000
75%,51.000000,2.000000,34.693750,2.000000,2.000000,3.000000,16639.912515
max,64.000000,2.000000,53.130000,5.000000,2.000000,4.000000,63770.428010

In [54]:
# check data there's any null
print(df_i.isnull().sum().max()) # max() for finding if there is not 0

0

In [55]:
X = df_i.drop('charges', axis=1)
y = df_i['charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [56]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [68]:
y_pred = model.predict(X_test)

In [67]:
print(f'Mean Squared Error: {mean_squared_error(y_test, y_pred)}')
print(f'R-squared: {round(r2_score(y_test, y_pred) * 100, 2)}%')

Mean Squared Error: 33805466.89868862
R-squared: 76.94%

---
##### Magic code for Convert to HTML
jupyter nbconvert --to html ./students-submissions/8936740/Lab3.ipynb --output-dir ./students-submissions/8936740 --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_input_tags="['noshow']"